### ISSUE TITLE
Verbose checks fail when using minimizer as a module

### ISSUE THREAD

**Issue by agroden** [agroden/python-minimizer#10]
Looks like this may be Python 3.6 only.  I tried it with Python 3.8, and the imports worked.

There is another error, however.
  File [redacted]/venv/lib/python3.8/site-packages/minimizer.py", line 214, in minimize
    grps = group_tokens(sbuf)
  File "[redacted]/venv/lib/python3.8/site-packages/minimizer.py", line 139, in group_tokens
    if verbose > 1:
NameError: name 'verbose' is not defined

Looks like global verbose is not being seen.

_Originally posted by @another2020githubuser in https://github.com/agroden/python-minimizer/issues/9#issuecomment-830659953_

**Comment by agroden** [comment]
Hopefully, 435759e fixes the issue you were seeing @another2020githubuser.

**Comment by another2020githubuser** [comment]
I'll give it a try and let you know.  Thanks again for the speedy reply.
