### ISSUE TITLE
2.0.1 fails install on Ubuntu 20.04

### ISSUE THREAD

**Issue by another2020githubuser** [agroden/python-minimizer#11]
I tried installing 2.0.1 via pip3, I get an error and end up with 2.0.0 installed.

Output:

<pre>Collecting python-minimizer
    Using cached python-minimizer-2.0.1.tar.gz (6.5 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
      Preparing wheel metadata ... error
  <font color="#CC0000">    ERROR: Command errored out with exit status 1:</font>
  <font color="#CC0000">     command: [redacted]/vcs/git/test-minimizer/venv/bin/python3 [redacted]/vcs/git/test-minimizer/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpwxc1txni</font>
  <font color="#CC0000">         cwd: /tmp/pip-install-_o3vpo7e/python-minimizer_dcbca966d3ea4ee1a2f2df2681149475</font>
  <font color="#CC0000">    Complete output (16 lines):</font>
  <font color="#CC0000">    Traceback (most recent call last):</font>
  <font color="#CC0000">      File &quot;[redacted]/vcs/git/test-minimizer/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py&quot;, line 280, in &lt;module&gt;</font>
  <font color="#CC0000">        main()</font>
  <font color="#CC0000">      File &quot;[redacted]/vcs/git/test-minimizer/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py&quot;, line 263, in main</font>
  <font color="#CC0000">        json_out[&apos;return_val&apos;] = hook(**hook_input[&apos;kwargs&apos;])</font>
  <font color="#CC0000">      File &quot;[redacted]/vcs/git/test-minimizer/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py&quot;, line 133, in prepare_metadata_for_build_wheel</font>
  <font color="#CC0000">        return hook(metadata_directory, config_settings)</font>
  <font color="#CC0000">      File &quot;/tmp/pip-build-env-sjlvgw0n/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py&quot;, line 44, in prepare_metadata_for_build_wheel</font>
  <font color="#CC0000">        builder = WheelBuilder(poetry)</font>
  <font color="#CC0000">      File &quot;/tmp/pip-build-env-sjlvgw0n/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py&quot;, line 57, in __init__</font>
  <font color="#CC0000">        super(WheelBuilder, self).__init__(poetry, executable=executable)</font>
  <font color="#CC0000">      File &quot;/tmp/pip-build-env-sjlvgw0n/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py&quot;, line 85, in __init__</font>
  <font color="#CC0000">        self._module = Module(</font>
  <font color="#CC0000">      File &quot;/tmp/pip-build-env-sjlvgw0n/overlay/lib/python3.8/site-packages/poetry/core/masonry/utils/module.py&quot;, line 63, in __init__</font>
  <font color="#CC0000">        raise ModuleOrPackageNotFound(</font>
  <font color="#CC0000">    poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package python-minimizer</font>
  <font color="#CC0000">    ----------------------------------------</font>
  <font color="#C4A000">WARNING: Discarding https://files.pythonhosted.org/packages/18/c0/883d5e7a44b2ddd7b98a2f2e140faaaf4f384d61b8bf91c5bb1ff8e5f2f5/python-minimizer-2.0.1.tar.gz#sha256=74aa842865cb821bfe3b2bcaf3c85a917c3234f98621fcdb7814fe2b5b42c639 (from https://pypi.org/simple/python-minimizer/). Command errored out with exit status 1: [redacted]/vcs/git/test-minimizer/venv/bin/python3 [redacted]/vcs/git/test-minimizer/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpwxc1txni Check the logs for full command output.</font>
    Using cached python_minimizer-2.0.0-py3-none-any.whl (6.8 kB)
  Installing collected packages: python-minimizer
  Successfully installed python-minimizer-2.0.0

And here is the output of pip freeze:

<pre>$ pip freeze
pkg-resources==0.0.0
python-minimizer==2.0.0
</pre>

Sorry to be a pest & thanks in advance

**Comment by agroden** [comment]
It is no problem! Honestly, it is nice to have someone to actually try it out. I apologize for the errors! I'm looking into this now.

**Comment by agroden** [comment]
Go ahead and give it a try now - I forgot to build the wheel in my haste to upload a fix. I just pushed the wheel up, hopefully this fixed the problem!

**Comment by another2020githubuser** [comment]
Worked perfectly!!  Thank you.  I really appreciate it.

```
$ pip3 install python-minimizer
Collecting python-minimizer
  Downloading python_minimizer-2.0.1-py3-none-any.whl (6.8 kB)
Installing collected packages: python-minimizer
Successfully installed python-minimizer-2.0.1
```

**Comment by agroden** [comment]
Awesome! I'm excited to help!
