### ISSUE TITLE
Minimizer can't import COMMENT and NL from token

### ISSUE THREAD

**Issue by another2020githubuser** [agroden/python-minimizer#9]
Hi, it looks like minimizer needs updating for Python 3.  From what I can see, COMMENT and NL have been removed from token.h in at least Python 3.6

When I run
(venv)$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minimizer import minimize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[redacted]/minimizer.py", line 10, in <module>
    from token import (
ImportError: cannot import name 'COMMENT'

If I modify minimizer.py as follows, the import succeeds, but crashes soon after as COMMENT and NL symbols are not defined.
 
from token import (
	#COMMENT,  <-- this import fails
	DEDENT,
	ENDMARKER,
	INDENT,
	NEWLINE,
	#NL,              <--  this import fails
	NAME,
	NUMBER,
	OP,
	STRING,
	tok_name
)

Hopefully this an easy fix.  I'd like to use this in a project I'm working on.

Best regards

**Comment by another2020githubuser** [comment]
Looks like this may be Python 3.6 only.  I tried it with Python 3.8, and the imports worked.

There is another error, however.
  File [redacted]/venv/lib/python3.8/site-packages/minimizer.py", line 214, in minimize
    grps = group_tokens(sbuf)
  File "[redacted]/venv/lib/python3.8/site-packages/minimizer.py", line 139, in group_tokens
    if verbose > 1:
NameError: name 'verbose' is not defined

Looks like global verbose is not being seen.

**Comment by agroden** [comment]
First, thank you for your interest in the python-minimizer! Now, let's get to the bottom of this...

I have attempted to repro this issue locally however I have 3.8 installed right now. When I check for COMMENT and NL, I get the following on Windows:

```python
$ python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from token import COMMENT, NL
>>> repr(COMMENT)
'60'
>>> repr(NL)
'61'
```

When I try it on Linux, I get:

```python
$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from token import COMMENT, NL
>>> repr(COMMENT)
'60'
>>> repr(NL)
'61'
```

I notice you are using a relatively old version of Python, even for 3.6. I'm not sure if it is even possible to download 3.6.9 anymore, but I'll take a look.

**Comment by agroden** [comment]
I see you are seeing a similar result, which is good. Allow me to make a second issue for the verbose flag.

**Comment by agroden** [comment]
Looks like a good option here is to make a note that 3.6 is an oddball and remove support on PyPi.

**Comment by agroden** [comment]
Final note, updated supported Python versions on PyPi: https://pypi.org/project/python-minimizer/

**Comment by another2020githubuser** [comment]
Thanks for the fast reply.
